[versions]
junit = "5.8.1"
jsoup = "1.17.2"
gson = "2.10.1"
slf4j = "2.0.12"

[libraries]
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-reload4j = { group = "org.slf4j", name = "slf4j-reload4j", version.ref = "slf4j" }

[plugins]